// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;

import org.openqa.selenium.chrome.ChromeDriver;

import org.openqa.selenium.Dimension;

import org.openqa.selenium.JavascriptExecutor;
import static org.junit.Assert.*;
import java.util.*;

public class Test2 {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "src/main/resources/chromedriver.exe");
        driver = new ChromeDriver();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void homework2() {
        driver.get("https://www.saucedemo.com/");
        driver.manage().window().setSize(new Dimension(1051, 740));
        driver.findElement(By.cssSelector("*[data-test=\"username\"]")).sendKeys("locked_out_user");
        driver.findElement(By.cssSelector("*[data-test=\"password\"]")).sendKeys("secret_sauce");
        driver.findElement(By.cssSelector("*[data-test=\"login-button\"]")).click();
        assertEquals ("Epic sadface: Sorry, this user has been locked out.", driver.findElement(By.cssSelector("*[data-test=\"error\"]")).getText());
    }

}

